In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r'C:\Users\shaik\Downloads\Bengaluru_House_Data.csv')

In [5]:
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [6]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [7]:
df.drop(columns=['society'],inplace=True)

In [8]:
df.dropna(inplace=True)

In [9]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [10]:
df['location']=df['location'].apply(lambda x:x.strip())

In [11]:
df.location.value_counts()

location
Whitefield                                         515
Sarjapur  Road                                     372
Electronic City                                    302
Kanakpura Road                                     261
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1254, dtype: int64

In [12]:
location_stats=df.groupby('location')['location'].agg('count').sort_values(ascending=False)

In [13]:
df.location.value_counts()

location
Whitefield                                         515
Sarjapur  Road                                     372
Electronic City                                    302
Kanakpura Road                                     261
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1254, dtype: int64

In [14]:
location_stats

location
Whitefield                 515
Sarjapur  Road             372
Electronic City            302
Kanakpura Road             261
Thanisandra                234
                          ...
mvj engineering college      1
manyata tech park            1
manyata                      1
kg halli jalhalli west       1
kanakapura road              1
Name: location, Length: 1254, dtype: int64

In [15]:
location_lessthan_10_entries=location_stats[location_stats<=10]

In [16]:
location_lessthan_10_entries

location
Basapura                   10
Gunjur Palya               10
Dairy Circle               10
HAL 2nd Stage              10
Kalkere                    10
                           ..
mvj engineering college     1
manyata tech park           1
manyata                     1
kg halli jalhalli west      1
kanakapura road             1
Name: location, Length: 1017, dtype: int64

In [17]:
df['location']=df['location'].apply(lambda x:'other' if x in location_lessthan_10_entries else x)

In [18]:
df['location'].value_counts()

location
other               2739
Whitefield           515
Sarjapur  Road       372
Electronic City      302
Kanakpura Road       261
                    ...
Marsur                11
Karuna Nagar          11
Prithvi Layout        11
Doddaballapur         11
Thyagaraja Nagar      11
Name: count, Length: 238, dtype: int64

In [19]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [20]:
df['size'].unique()

<ArrowStringArray>
[     '2 BHK',  '4 Bedroom',      '3 BHK',  '3 Bedroom',      '1 BHK',
       '1 RK',      '4 BHK',  '1 Bedroom',  '2 Bedroom',  '6 Bedroom',
  '8 Bedroom',  '7 Bedroom',      '5 BHK',      '7 BHK',      '6 BHK',
  '5 Bedroom',     '11 BHK',      '9 BHK',  '9 Bedroom',     '27 BHK',
 '11 Bedroom', '43 Bedroom',     '14 BHK',      '8 BHK', '12 Bedroom',
 '10 Bedroom',     '13 BHK']
Length: 27, dtype: str

In [21]:
df['bedrooms']=df['size'].apply(lambda x:int(x.split(' ')[0]))

In [22]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price,bedrooms
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00,3
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00,5
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00,1

In [23]:
df.	total_sqft.unique()

<ArrowStringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '1310',        '1800',        '2785',        '1000',
 ...
        '1648',        '1379',        '3124',         '613',         '250',
        '2395',        '2758', '1133 - 1384',         '774',        '4689']
Length: 1976, dtype: str

In [24]:
def clean(sqft):
    tokens = sqft.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1]))/2
    else:
        try:
            return float(sqft)
        except:
            return None

In [25]:
df['total_sqft']=df['total_sqft'].apply(clean)

In [26]:
df['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ], shape=(1887,))

In [27]:
df.dropna(inplace=True)

In [28]:
df.describe()

         total_sqft          bath       balcony         price      bedrooms
count  12668.000000  12668.000000  12668.000000  12668.000000  12668.000000
mean    1511.835167      2.616277      1.585649    105.952648      2.736422
std     1162.097276      1.223882      0.816758    131.813137      1.202643
min        5.000000      1.000000      0.000000      8.000000      1.000000
25%     1100.000000      2.000000      1.000000     49.015000      2.000000
50%     1260.000000      2.000000      2.000000     70.000000      3.000000
75%     1640.000000      3.000000      2.000000    115.000000      3.000000
max    52272.000000     40.000000      3.000000   2912.000000     43.000000

In [29]:
df['sqft_per_bedroom']=df['total_sqft']/df['bedrooms']

In [30]:
df.sqft_per_bedroom.describe()

count    12668.000000
mean       570.060291
std        380.298999
min          0.714286
25%        473.333333
50%        550.000000
75%        622.500000
max      26136.000000
Name: sqft_per_bedroom, dtype: float64

In [31]:
df2=df[df['sqft_per_bedroom'] >=300]

In [32]:
df2

,area_type,availability,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bedroom
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000
...,...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000

In [33]:
df2['price_per_sqft'] = round(df2['price']*100000/df2['total_sqft'],2)

In [34]:
df2.price_per_sqft.describe()

count     12013.000000
mean       6206.082361
std        3985.518849
min         267.830000
25%        4199.360000
50%        5252.530000
75%        6823.530000
max      176470.590000
Name: price_per_sqft, dtype: float64

In [35]:
df3 = df2 [df2['price_per_sqft'] >= 2000]

In [36]:
df3

,area_type,availability,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bedroom,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000,3699.81
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000,4615.38
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000,4305.56
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000,6245.89
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000,4250.00
...,...,...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667,6530.61
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000,6689.83
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000,5258.55
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000,10407.34
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000,3090.91

In [37]:
df3.drop(columns = ['size', 'sqft_per_bedroom', 'price_per_sqft'])

,area_type,availability,location,total_sqft,bath,balcony,price,bedrooms
0,Super built-up Area,19-Dec,Electronic City Phase II,1056.0,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,1440.0,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,1200.0,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,1715.0,3.0,3.0,112.00,3
13315,Built-up Area,Ready To Move,Whitefield,3453.0,4.0,0.0,231.00,5
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,1141.0,2.0,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4689.0,4.0,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,550.0,1.0,1.0,17.00,1

In [38]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
from sklearn.linear_model import LinearRegression

In [41]:
from sklearn.pipeline import make_pipeline

In [42]:
from sklearn.compose import make_column_transformer

In [43]:
col_trans = make_column_transformer(
    (
        OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
        ['area_type', 'availability', 'location', 'size']
    ),
    remainder='passthrough'
)

In [44]:
lr = LinearRegression()

In [45]:
scaler = StandardScaler()

In [46]:
pipe = make_pipeline(
    col_trans,
    StandardScaler(with_mean=False),
    LinearRegression()
)

In [47]:
data_input = df3.drop(columns=['price'])
data_output = df3['price']

In [48]:
x_train, x_test, y_train, y_test = train_test_split(data_input, data_output, test_size=0.2)

In [49]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['area_type', 'availability',
                                                   'location', 'size'])])),
                ('standardscaler', StandardScaler(with_mean=False)),
                ('linearregression', LinearRegression())])

In [50]:
pipe.score(x_test, y_test)

0.7940571653976745

In [51]:
input=pd.DataFrame([['Electronic City Phase II', 1500.0, 3.0, 2.0, 3]], columns=['location', 'total_sqft', 'bath', 'balcony', 'bedrooms'])

In [52]:
import pandas as pd

# Sample house details
custom_house = {
    'area_type': 'Super built-up  Area',
    'availability': 'Ready To Move',
    'location': 'Electronic City',
    'size': '2 BHK',
    'total_sqft': 1200.0,
    'bath': 2,
    'balcony': 1,
    'bedrooms': 2,
    'sqft_per_bedroom': 600.0,
    'price_per_sqft': 4500.0
}

# Create DataFrame
input_df = pd.DataFrame([custom_house])

# Reorder columns to match the training data
input_df = input_df[x_train.columns]

# Predict
prediction = pipe.predict(input_df)

print("Predicted Price:", prediction[0])

Predicted Price: 59.662196235572324

In [53]:
pipe.predict(input_df)

array([59.66219624])

In [57]:
import pickle as pk

In [58]:
pk.dump(pipe,open('prediction_model10','wb'))

In [59]:
df3.to_csv('Cleaned_data.csv')

In [ ]:

# PS C:\Users\shaik> cd "C:\Users\shaik\.ipynb_checkpoints\project"
# PS C:\Users\shaik\.ipynb_checkpoints\project> python -m streamlit run app.py